/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as LoggedInImport } from './routes/_logged-in'
import { Route as LoggedInIndexImport } from './routes/_logged-in/index'
import { Route as LoggedInForbiddenImport } from './routes/_logged-in/forbidden'
import { Route as LoggedInCreateImport } from './routes/_logged-in/create'
import { Route as LoggedInYearIdImport } from './routes/_logged-in/$yearId'
import { Route as LoggedInUsersIndexImport } from './routes/_logged-in/users/index'
import { Route as LoggedInYearIdIndexImport } from './routes/_logged-in/$yearId/index'
import { Route as LoggedInUsersUserIdImport } from './routes/_logged-in/users/$userId'
import { Route as LoggedInYearIdSettingsImport } from './routes/_logged-in/$yearId/settings'
import { Route as LoggedInYearIdResultsImport } from './routes/_logged-in/$yearId/results'
import { Route as LoggedInYearIdRegistrationFormsImport } from './routes/_logged-in/$yearId/registration-forms'
import { Route as LoggedInYearIdRegistrationImport } from './routes/_logged-in/$yearId/registration'
import { Route as LoggedInYearIdContactsImport } from './routes/_logged-in/$yearId/contacts'
import { Route as LoggedInYearIdAttendanceImport } from './routes/_logged-in/$yearId/attendance'
import { Route as LoggedInYearIdDaysDayIdIndexImport } from './routes/_logged-in/$yearId/days/$dayId/index'
import { Route as LoggedInYearIdDaysDayIdEditImport } from './routes/_logged-in/$yearId/days/$dayId/edit'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LoggedInRoute = LoggedInImport.update({
  id: '/_logged-in',
  getParentRoute: () => rootRoute,
} as any)

const LoggedInIndexRoute = LoggedInIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoggedInRoute,
} as any)

const LoggedInForbiddenRoute = LoggedInForbiddenImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => LoggedInRoute,
} as any)

const LoggedInCreateRoute = LoggedInCreateImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => LoggedInRoute,
} as any)

const LoggedInYearIdRoute = LoggedInYearIdImport.update({
  id: '/$yearId',
  path: '/$yearId',
  getParentRoute: () => LoggedInRoute,
} as any)

const LoggedInUsersIndexRoute = LoggedInUsersIndexImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => LoggedInRoute,
} as any)

const LoggedInYearIdIndexRoute = LoggedInYearIdIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoggedInYearIdRoute,
} as any)

const LoggedInUsersUserIdRoute = LoggedInUsersUserIdImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => LoggedInRoute,
} as any)

const LoggedInYearIdSettingsRoute = LoggedInYearIdSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LoggedInYearIdRoute,
} as any)

const LoggedInYearIdResultsRoute = LoggedInYearIdResultsImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => LoggedInYearIdRoute,
} as any)

const LoggedInYearIdRegistrationFormsRoute =
  LoggedInYearIdRegistrationFormsImport.update({
    id: '/registration-forms',
    path: '/registration-forms',
    getParentRoute: () => LoggedInYearIdRoute,
  } as any)

const LoggedInYearIdRegistrationRoute = LoggedInYearIdRegistrationImport.update(
  {
    id: '/registration',
    path: '/registration',
    getParentRoute: () => LoggedInYearIdRoute,
  } as any,
)

const LoggedInYearIdContactsRoute = LoggedInYearIdContactsImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => LoggedInYearIdRoute,
} as any)

const LoggedInYearIdAttendanceRoute = LoggedInYearIdAttendanceImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => LoggedInYearIdRoute,
} as any)

const LoggedInYearIdDaysDayIdIndexRoute =
  LoggedInYearIdDaysDayIdIndexImport.update({
    id: '/days/$dayId/',
    path: '/days/$dayId/',
    getParentRoute: () => LoggedInYearIdRoute,
  } as any)

const LoggedInYearIdDaysDayIdEditRoute =
  LoggedInYearIdDaysDayIdEditImport.update({
    id: '/days/$dayId/edit',
    path: '/days/$dayId/edit',
    getParentRoute: () => LoggedInYearIdRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_logged-in': {
      id: '/_logged-in'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LoggedInImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_logged-in/$yearId': {
      id: '/_logged-in/$yearId'
      path: '/$yearId'
      fullPath: '/$yearId'
      preLoaderRoute: typeof LoggedInYearIdImport
      parentRoute: typeof LoggedInImport
    }
    '/_logged-in/create': {
      id: '/_logged-in/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof LoggedInCreateImport
      parentRoute: typeof LoggedInImport
    }
    '/_logged-in/forbidden': {
      id: '/_logged-in/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof LoggedInForbiddenImport
      parentRoute: typeof LoggedInImport
    }
    '/_logged-in/': {
      id: '/_logged-in/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LoggedInIndexImport
      parentRoute: typeof LoggedInImport
    }
    '/_logged-in/$yearId/attendance': {
      id: '/_logged-in/$yearId/attendance'
      path: '/attendance'
      fullPath: '/$yearId/attendance'
      preLoaderRoute: typeof LoggedInYearIdAttendanceImport
      parentRoute: typeof LoggedInYearIdImport
    }
    '/_logged-in/$yearId/contacts': {
      id: '/_logged-in/$yearId/contacts'
      path: '/contacts'
      fullPath: '/$yearId/contacts'
      preLoaderRoute: typeof LoggedInYearIdContactsImport
      parentRoute: typeof LoggedInYearIdImport
    }
    '/_logged-in/$yearId/registration': {
      id: '/_logged-in/$yearId/registration'
      path: '/registration'
      fullPath: '/$yearId/registration'
      preLoaderRoute: typeof LoggedInYearIdRegistrationImport
      parentRoute: typeof LoggedInYearIdImport
    }
    '/_logged-in/$yearId/registration-forms': {
      id: '/_logged-in/$yearId/registration-forms'
      path: '/registration-forms'
      fullPath: '/$yearId/registration-forms'
      preLoaderRoute: typeof LoggedInYearIdRegistrationFormsImport
      parentRoute: typeof LoggedInYearIdImport
    }
    '/_logged-in/$yearId/results': {
      id: '/_logged-in/$yearId/results'
      path: '/results'
      fullPath: '/$yearId/results'
      preLoaderRoute: typeof LoggedInYearIdResultsImport
      parentRoute: typeof LoggedInYearIdImport
    }
    '/_logged-in/$yearId/settings': {
      id: '/_logged-in/$yearId/settings'
      path: '/settings'
      fullPath: '/$yearId/settings'
      preLoaderRoute: typeof LoggedInYearIdSettingsImport
      parentRoute: typeof LoggedInYearIdImport
    }
    '/_logged-in/users/$userId': {
      id: '/_logged-in/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof LoggedInUsersUserIdImport
      parentRoute: typeof LoggedInImport
    }
    '/_logged-in/$yearId/': {
      id: '/_logged-in/$yearId/'
      path: '/'
      fullPath: '/$yearId/'
      preLoaderRoute: typeof LoggedInYearIdIndexImport
      parentRoute: typeof LoggedInYearIdImport
    }
    '/_logged-in/users/': {
      id: '/_logged-in/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof LoggedInUsersIndexImport
      parentRoute: typeof LoggedInImport
    }
    '/_logged-in/$yearId/days/$dayId/edit': {
      id: '/_logged-in/$yearId/days/$dayId/edit'
      path: '/days/$dayId/edit'
      fullPath: '/$yearId/days/$dayId/edit'
      preLoaderRoute: typeof LoggedInYearIdDaysDayIdEditImport
      parentRoute: typeof LoggedInYearIdImport
    }
    '/_logged-in/$yearId/days/$dayId/': {
      id: '/_logged-in/$yearId/days/$dayId/'
      path: '/days/$dayId'
      fullPath: '/$yearId/days/$dayId'
      preLoaderRoute: typeof LoggedInYearIdDaysDayIdIndexImport
      parentRoute: typeof LoggedInYearIdImport
    }
  }
}

// Create and export the route tree

interface LoggedInYearIdRouteChildren {
  LoggedInYearIdAttendanceRoute: typeof LoggedInYearIdAttendanceRoute
  LoggedInYearIdContactsRoute: typeof LoggedInYearIdContactsRoute
  LoggedInYearIdRegistrationRoute: typeof LoggedInYearIdRegistrationRoute
  LoggedInYearIdRegistrationFormsRoute: typeof LoggedInYearIdRegistrationFormsRoute
  LoggedInYearIdResultsRoute: typeof LoggedInYearIdResultsRoute
  LoggedInYearIdSettingsRoute: typeof LoggedInYearIdSettingsRoute
  LoggedInYearIdIndexRoute: typeof LoggedInYearIdIndexRoute
  LoggedInYearIdDaysDayIdEditRoute: typeof LoggedInYearIdDaysDayIdEditRoute
  LoggedInYearIdDaysDayIdIndexRoute: typeof LoggedInYearIdDaysDayIdIndexRoute
}

const LoggedInYearIdRouteChildren: LoggedInYearIdRouteChildren = {
  LoggedInYearIdAttendanceRoute: LoggedInYearIdAttendanceRoute,
  LoggedInYearIdContactsRoute: LoggedInYearIdContactsRoute,
  LoggedInYearIdRegistrationRoute: LoggedInYearIdRegistrationRoute,
  LoggedInYearIdRegistrationFormsRoute: LoggedInYearIdRegistrationFormsRoute,
  LoggedInYearIdResultsRoute: LoggedInYearIdResultsRoute,
  LoggedInYearIdSettingsRoute: LoggedInYearIdSettingsRoute,
  LoggedInYearIdIndexRoute: LoggedInYearIdIndexRoute,
  LoggedInYearIdDaysDayIdEditRoute: LoggedInYearIdDaysDayIdEditRoute,
  LoggedInYearIdDaysDayIdIndexRoute: LoggedInYearIdDaysDayIdIndexRoute,
}

const LoggedInYearIdRouteWithChildren = LoggedInYearIdRoute._addFileChildren(
  LoggedInYearIdRouteChildren,
)

interface LoggedInRouteChildren {
  LoggedInYearIdRoute: typeof LoggedInYearIdRouteWithChildren
  LoggedInCreateRoute: typeof LoggedInCreateRoute
  LoggedInForbiddenRoute: typeof LoggedInForbiddenRoute
  LoggedInIndexRoute: typeof LoggedInIndexRoute
  LoggedInUsersUserIdRoute: typeof LoggedInUsersUserIdRoute
  LoggedInUsersIndexRoute: typeof LoggedInUsersIndexRoute
}

const LoggedInRouteChildren: LoggedInRouteChildren = {
  LoggedInYearIdRoute: LoggedInYearIdRouteWithChildren,
  LoggedInCreateRoute: LoggedInCreateRoute,
  LoggedInForbiddenRoute: LoggedInForbiddenRoute,
  LoggedInIndexRoute: LoggedInIndexRoute,
  LoggedInUsersUserIdRoute: LoggedInUsersUserIdRoute,
  LoggedInUsersIndexRoute: LoggedInUsersIndexRoute,
}

const LoggedInRouteWithChildren = LoggedInRoute._addFileChildren(
  LoggedInRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof LoggedInRouteWithChildren
  '/login': typeof LoginRoute
  '/$yearId': typeof LoggedInYearIdRouteWithChildren
  '/create': typeof LoggedInCreateRoute
  '/forbidden': typeof LoggedInForbiddenRoute
  '/': typeof LoggedInIndexRoute
  '/$yearId/attendance': typeof LoggedInYearIdAttendanceRoute
  '/$yearId/contacts': typeof LoggedInYearIdContactsRoute
  '/$yearId/registration': typeof LoggedInYearIdRegistrationRoute
  '/$yearId/registration-forms': typeof LoggedInYearIdRegistrationFormsRoute
  '/$yearId/results': typeof LoggedInYearIdResultsRoute
  '/$yearId/settings': typeof LoggedInYearIdSettingsRoute
  '/users/$userId': typeof LoggedInUsersUserIdRoute
  '/$yearId/': typeof LoggedInYearIdIndexRoute
  '/users': typeof LoggedInUsersIndexRoute
  '/$yearId/days/$dayId/edit': typeof LoggedInYearIdDaysDayIdEditRoute
  '/$yearId/days/$dayId': typeof LoggedInYearIdDaysDayIdIndexRoute
}

export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/create': typeof LoggedInCreateRoute
  '/forbidden': typeof LoggedInForbiddenRoute
  '/': typeof LoggedInIndexRoute
  '/$yearId/attendance': typeof LoggedInYearIdAttendanceRoute
  '/$yearId/contacts': typeof LoggedInYearIdContactsRoute
  '/$yearId/registration': typeof LoggedInYearIdRegistrationRoute
  '/$yearId/registration-forms': typeof LoggedInYearIdRegistrationFormsRoute
  '/$yearId/results': typeof LoggedInYearIdResultsRoute
  '/$yearId/settings': typeof LoggedInYearIdSettingsRoute
  '/users/$userId': typeof LoggedInUsersUserIdRoute
  '/$yearId': typeof LoggedInYearIdIndexRoute
  '/users': typeof LoggedInUsersIndexRoute
  '/$yearId/days/$dayId/edit': typeof LoggedInYearIdDaysDayIdEditRoute
  '/$yearId/days/$dayId': typeof LoggedInYearIdDaysDayIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_logged-in': typeof LoggedInRouteWithChildren
  '/login': typeof LoginRoute
  '/_logged-in/$yearId': typeof LoggedInYearIdRouteWithChildren
  '/_logged-in/create': typeof LoggedInCreateRoute
  '/_logged-in/forbidden': typeof LoggedInForbiddenRoute
  '/_logged-in/': typeof LoggedInIndexRoute
  '/_logged-in/$yearId/attendance': typeof LoggedInYearIdAttendanceRoute
  '/_logged-in/$yearId/contacts': typeof LoggedInYearIdContactsRoute
  '/_logged-in/$yearId/registration': typeof LoggedInYearIdRegistrationRoute
  '/_logged-in/$yearId/registration-forms': typeof LoggedInYearIdRegistrationFormsRoute
  '/_logged-in/$yearId/results': typeof LoggedInYearIdResultsRoute
  '/_logged-in/$yearId/settings': typeof LoggedInYearIdSettingsRoute
  '/_logged-in/users/$userId': typeof LoggedInUsersUserIdRoute
  '/_logged-in/$yearId/': typeof LoggedInYearIdIndexRoute
  '/_logged-in/users/': typeof LoggedInUsersIndexRoute
  '/_logged-in/$yearId/days/$dayId/edit': typeof LoggedInYearIdDaysDayIdEditRoute
  '/_logged-in/$yearId/days/$dayId/': typeof LoggedInYearIdDaysDayIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/$yearId'
    | '/create'
    | '/forbidden'
    | '/'
    | '/$yearId/attendance'
    | '/$yearId/contacts'
    | '/$yearId/registration'
    | '/$yearId/registration-forms'
    | '/$yearId/results'
    | '/$yearId/settings'
    | '/users/$userId'
    | '/$yearId/'
    | '/users'
    | '/$yearId/days/$dayId/edit'
    | '/$yearId/days/$dayId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/create'
    | '/forbidden'
    | '/'
    | '/$yearId/attendance'
    | '/$yearId/contacts'
    | '/$yearId/registration'
    | '/$yearId/registration-forms'
    | '/$yearId/results'
    | '/$yearId/settings'
    | '/users/$userId'
    | '/$yearId'
    | '/users'
    | '/$yearId/days/$dayId/edit'
    | '/$yearId/days/$dayId'
  id:
    | '__root__'
    | '/_logged-in'
    | '/login'
    | '/_logged-in/$yearId'
    | '/_logged-in/create'
    | '/_logged-in/forbidden'
    | '/_logged-in/'
    | '/_logged-in/$yearId/attendance'
    | '/_logged-in/$yearId/contacts'
    | '/_logged-in/$yearId/registration'
    | '/_logged-in/$yearId/registration-forms'
    | '/_logged-in/$yearId/results'
    | '/_logged-in/$yearId/settings'
    | '/_logged-in/users/$userId'
    | '/_logged-in/$yearId/'
    | '/_logged-in/users/'
    | '/_logged-in/$yearId/days/$dayId/edit'
    | '/_logged-in/$yearId/days/$dayId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LoggedInRoute: typeof LoggedInRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  LoggedInRoute: LoggedInRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_logged-in",
        "/login"
      ]
    },
    "/_logged-in": {
      "filePath": "_logged-in.tsx",
      "children": [
        "/_logged-in/$yearId",
        "/_logged-in/create",
        "/_logged-in/forbidden",
        "/_logged-in/",
        "/_logged-in/users/$userId",
        "/_logged-in/users/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_logged-in/$yearId": {
      "filePath": "_logged-in/$yearId.tsx",
      "parent": "/_logged-in",
      "children": [
        "/_logged-in/$yearId/attendance",
        "/_logged-in/$yearId/contacts",
        "/_logged-in/$yearId/registration",
        "/_logged-in/$yearId/registration-forms",
        "/_logged-in/$yearId/results",
        "/_logged-in/$yearId/settings",
        "/_logged-in/$yearId/",
        "/_logged-in/$yearId/days/$dayId/edit",
        "/_logged-in/$yearId/days/$dayId/"
      ]
    },
    "/_logged-in/create": {
      "filePath": "_logged-in/create.tsx",
      "parent": "/_logged-in"
    },
    "/_logged-in/forbidden": {
      "filePath": "_logged-in/forbidden.tsx",
      "parent": "/_logged-in"
    },
    "/_logged-in/": {
      "filePath": "_logged-in/index.tsx",
      "parent": "/_logged-in"
    },
    "/_logged-in/$yearId/attendance": {
      "filePath": "_logged-in/$yearId/attendance.tsx",
      "parent": "/_logged-in/$yearId"
    },
    "/_logged-in/$yearId/contacts": {
      "filePath": "_logged-in/$yearId/contacts.tsx",
      "parent": "/_logged-in/$yearId"
    },
    "/_logged-in/$yearId/registration": {
      "filePath": "_logged-in/$yearId/registration.tsx",
      "parent": "/_logged-in/$yearId"
    },
    "/_logged-in/$yearId/registration-forms": {
      "filePath": "_logged-in/$yearId/registration-forms.tsx",
      "parent": "/_logged-in/$yearId"
    },
    "/_logged-in/$yearId/results": {
      "filePath": "_logged-in/$yearId/results.tsx",
      "parent": "/_logged-in/$yearId"
    },
    "/_logged-in/$yearId/settings": {
      "filePath": "_logged-in/$yearId/settings.tsx",
      "parent": "/_logged-in/$yearId"
    },
    "/_logged-in/users/$userId": {
      "filePath": "_logged-in/users/$userId.tsx",
      "parent": "/_logged-in"
    },
    "/_logged-in/$yearId/": {
      "filePath": "_logged-in/$yearId/index.tsx",
      "parent": "/_logged-in/$yearId"
    },
    "/_logged-in/users/": {
      "filePath": "_logged-in/users/index.tsx",
      "parent": "/_logged-in"
    },
    "/_logged-in/$yearId/days/$dayId/edit": {
      "filePath": "_logged-in/$yearId/days/$dayId/edit.tsx",
      "parent": "/_logged-in/$yearId"
    },
    "/_logged-in/$yearId/days/$dayId/": {
      "filePath": "_logged-in/$yearId/days/$dayId/index.tsx",
      "parent": "/_logged-in/$yearId"
    }
  }
}
ROUTE_MANIFEST_END */
