"""make manager positions

Revision ID: cd2a2b0b1b25
Revises: eef28c0cd39e
Create Date: 2025-11-16 11:22:02.373174

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cd2a2b0b1b25"
down_revision: str | None = "eef28c0cd39e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "positions", sa.Column("is_manager", sa.Boolean(), nullable=False, server_default="false")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("positions", "is_manager")
    # ### end Alembic commands ###
