"""remove_experience_field_from_application_form

Revision ID: 2beb515f444b
Revises: ed61a9a0344a
Create Date: 2025-12-05 01:58:11.732810

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "2beb515f444b"
down_revision: str | None = "ed61a9a0344a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
