"""Add gender to users

Revision ID: 8e31dc6646bd
Revises: cd2a2b0b1b25
Create Date: 2025-11-30 21:51:47.987287

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8e31dc6646bd"
down_revision: str | None = "cd2a2b0b1b25"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("gender", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "gender")
    # ### end Alembic commands ###
