"""Add score and description to Position

Revision ID: 81c24b11a34f
Revises: 2beb515f444b
Create Date: 2025-12-05 20:04:20.977355

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "81c24b11a34f"
down_revision: str | None = "2beb515f444b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "positions", sa.Column("score", sa.Double(), nullable=False, server_default="1.0")
    )
    op.add_column("positions", sa.Column("description", sa.String(), nullable=True))
    op.drop_column("application_forms", "experience")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "application_forms",
        sa.Column(
            "experience",
            sa.DOUBLE_PRECISION(precision=53),
            server_default=sa.text("'0'::double precision"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("positions", "description")
    op.drop_column("positions", "score")
    # ### end Alembic commands ###
