"""add experience field to application form

Revision ID: ed61a9a0344a
Revises: f474eb5497c4
Create Date: 2025-12-04 22:35:29.972041

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ed61a9a0344a"
down_revision: str | None = "f474eb5497c4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "application_forms",
        sa.Column("experience", sa.Double(), server_default="0.0", nullable=False),
    )
    op.alter_column(
        "assessments",
        "value",
        existing_type=sa.NUMERIC(precision=5, scale=2),
        type_=sa.Double(),
        existing_nullable=False,
    )
    # Removed: op.drop_column('users', 'photo') - column may not exist
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed: op.add_column('users', sa.Column('photo', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column(
        "assessments",
        "value",
        existing_type=sa.Double(),
        type_=sa.NUMERIC(precision=5, scale=2),
        existing_nullable=False,
    )
    op.drop_column("application_forms", "experience")
    # ### end Alembic commands ###
