"""add score to positions

Revision ID: dd5145b00290
Revises: f1c13aace233
Create Date: 2025-12-05 20:49:31.916742

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dd5145b00290"
down_revision: str | None = "f1c13aace233"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "positions", sa.Column("score", sa.Double(), server_default="1.0", nullable=False)
    )
    op.add_column("positions", sa.Column("description", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("positions", "description")
    op.drop_column("positions", "score")
    # ### end Alembic commands ###
