"""allow_fractional_assessment_values

Revision ID: f474eb5497c4
Revises: 1006dcfcc630
Create Date: 2025-12-04 20:27:09.052379

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f474eb5497c4"
down_revision: str | None = "1006dcfcc630"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "assessments",
        "value",
        existing_type=sa.INTEGER(),
        type_=sa.Numeric(precision=5, scale=2),
        existing_nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "assessments",
        "value",
        existing_type=sa.Numeric(precision=5, scale=2),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
