// This file is auto-generated by @hey-api/openapi-ts

export type AddAssessmentRequest = {
    user_day_id: number;
    comment: string;
    value: number;
};

export type AddAssessmentResponse = {
    success: true;
    assessment_id: number;
};

export type AddDayRequest = {
    year_id: number;
    name: string;
    information: string;
    score: number;
    mandatory: boolean;
    assignment_published: boolean;
};

export type AddDayResponse = {
    success: true;
    day_id: number;
};

export type AddHallRequest = {
    year_id: number;
    name: string;
    description?: string | null;
};

export type AddHallResponse = {
    success: true;
    hall_id: number;
};

export type AddPositionRequest = {
    year_id: number;
    name: string;
    can_desire?: boolean;
    has_halls?: boolean;
    is_manager?: boolean;
};

export type AddPositionResponse = {
    success: true;
    position_id: number;
};

export type AddUserDayRequest = {
    application_form_id: number;
    day_id: number;
    information: string;
    position_id: number;
    hall_id?: number | null;
};

export type AddUserDayResponse = {
    success: true;
    user_day_id: number;
};

export type AddYearRequest = {
    year_name: string;
};

export type AddYearResponse = {
    success: true;
    year_id: number;
};

export type AllAttendanceResponse = {
    attendance: Array<AttendanceItem>;
};

export type AllUsersResponse = {
    users: Array<VolunteersApiV1AdminUserSchemasUserResponse>;
};

export type ApplicationFormYearSaveRequest = {
    desired_positions_ids: Array<number>;
    itmo_group?: string | null;
    comments?: string;
    needs_invitation?: boolean;
};

export type ApplicationFormYearSavedResponse = {
    success: true;
    positions: Array<PositionOut>;
    days: Array<DayOutUser>;
    desired_positions: Array<PositionOut>;
    itmo_group: string | null;
    comments: string;
    needs_invitation: boolean;
    open_for_registration: boolean;
};

export type AssessmentItem = {
    assessment_id: number;
    user_day_id: number;
    comment: string;
    value: number;
};

export type AssessmentsResponse = {
    assessments: Array<AssessmentItem>;
};

export type AssignmentItem = {
    user_day_id: number;
    application_form_id: number;
    position_id: number;
    hall_id: number | null;
};

export type AssignmentsResponse = {
    assignments: Array<AssignmentItem>;
};

export type Attendance = 'yes' | 'no' | 'late' | 'sick' | 'unknown';

export type AttendanceItem = {
    user_day_id: number;
    day_id: number;
    day_name: string;
    user_id: number;
    user_name: string;
    user_telegram: string | null;
    position_id: number;
    position_name: string;
    hall_id: number | null;
    hall_name: string | null;
    attendance: Attendance;
};

export type CopyAssignmentsRequest = {
    source_day_id: number;
    target_day_id: number;
    overwrite_existing?: boolean;
    replace_all?: boolean;
};

export type CopyAssignmentsResponse = {
    success: true;
    copied_count: number;
};

/**
 * Simplified day assignment item for user-facing API
 */
export type DayAssignmentItem = {
    name: string;
    telegram: string | null;
    position: string;
    hall: string | null;
};

/**
 * Response containing a plain array of day assignments
 */
export type DayAssignmentsResponse = {
    assignments: Array<DayAssignmentItem>;
    is_published: boolean;
};

export type DayOutAdmin = {
    day_id: number;
    year_id: number;
    name: string;
    information: string;
    score: number | null;
    mandatory: boolean;
    assignment_published: boolean;
};

export type DayOutUser = {
    day_id: number;
    name: string;
};

export type EditAssessmentRequest = {
    comment?: string | null;
    value?: number | null;
};

export type EditDayRequest = {
    name?: string | null;
    information?: string | null;
    score?: number | null;
    mandatory?: boolean | null;
    assignment_published?: boolean | null;
};

export type EditHallRequest = {
    name?: string | null;
    description?: string | null;
};

export type EditPositionRequest = {
    name?: string | null;
    can_desire?: boolean | null;
    has_halls?: boolean | null;
    is_manager?: boolean | null;
};

export type EditUserDayRequest = {
    information?: string | null;
    position_id: number;
    hall_id?: number | null;
};

export type EditUserRequest = {
    first_name_ru?: string | null;
    last_name_ru?: string | null;
    first_name_en?: string | null;
    last_name_en?: string | null;
    isu_id?: number | null;
    patronymic_ru?: string | null;
    phone?: string | null;
    email?: string | null;
    telegram_username?: string | null;
    is_admin?: boolean | null;
    telegram_id?: number | null;
};

export type EditYearRequest = {
    year_name?: string | null;
    open_for_registration?: boolean | null;
};

export type ErrorLoginResponse = {
    success: false;
    description: string;
};

export type ExperienceItem = {
    year_name: string;
    positions: Array<string>;
    attendance_stats: {
        [key: string]: number;
    };
    assessments: Array<string>;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type HallOut = {
    year_id: number;
    name: string;
    description?: string | null;
    hall_id: number;
};

export type PositionOut = {
    year_id: number;
    name: string;
    can_desire: boolean;
    has_halls: boolean;
    is_manager: boolean;
    position_id: number;
};

export type RefreshTokenRequest = {
    refresh_token: string;
};

export type RegistrationFormItem = {
    form_id: number;
    user_id: number;
    first_name_ru: string;
    last_name_ru: string;
    patronymic_ru: string | null;
    first_name_en: string;
    last_name_en: string;
    isu_id: number | null;
    phone: string | null;
    email: string | null;
    telegram_username: string | null;
    itmo_group: string | null;
    comments: string;
    needs_invitation: boolean;
    desired_positions: Array<PositionOut>;
    experience: Array<ExperienceItem>;
    created_at: string;
    updated_at: string;
};

export type RegistrationFormsResponse = {
    forms: Array<RegistrationFormItem>;
};

export type RegistrationRequest = {
    telegram_id: number;
    telegram_auth_date: number;
    telegram_first_name: string;
    telegram_hash: string;
    telegram_last_name?: string | null;
    telegram_username?: string | null;
    telegram_photo_url?: string | null;
    first_name_ru: string;
    last_name_ru: string;
    first_name_en: string;
    last_name_en: string;
    isu_id?: number | null;
    patronymic_ru?: string | null;
    phone?: string | null;
    email?: string | null;
};

export type SaveDayAttendanceRequest = {
    user_day_id: number;
    attendance: Attendance;
};

export type SuccessfulLoginResponse = {
    success: true;
    token: string;
    refresh_token: string;
    expires_in: number;
    refresh_expires_in: number;
};

export type TelegramLoginRequest = {
    telegram_id: number;
    telegram_auth_date: number;
    telegram_first_name: string;
    telegram_hash: string;
    telegram_last_name?: string | null;
    telegram_username?: string | null;
    telegram_photo_url?: string | null;
};

export type TelegramMigrateRequest = {
    telegram_id: number;
    telegram_auth_date: number;
    telegram_first_name: string;
    telegram_hash: string;
    telegram_last_name?: string | null;
    telegram_username?: string | null;
    telegram_photo_url?: string | null;
    email: string;
    password: string;
};

export type UserListItem = {
    id: number;
    first_name_ru: string;
    last_name_ru: string;
    patronymic_ru: string | null;
    first_name_en: string;
    last_name_en: string;
    itmo_group: string | null;
    email: string | null;
    phone: string | null;
    telegram_username: string | null;
    is_registered: boolean;
};

export type UserListResponse = {
    users: Array<UserListItem>;
};

export type UserUpdateRequest = {
    first_name_ru?: string | null;
    last_name_ru?: string | null;
    first_name_en?: string | null;
    last_name_en?: string | null;
    isu_id?: number | null;
    patronymic_ru?: string | null;
    phone?: string | null;
    email?: string | null;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type YearOut = {
    year_name: string;
    open_for_registration: boolean;
    year_id: number;
    is_manager: boolean;
};

export type YearsResponse = {
    success: true;
    years: Array<YearOut>;
};

export type VolunteersApiV1AdminUserSchemasUserResponse = {
    user_id: number;
    telegram_id: number | null;
    first_name_ru: string;
    last_name_ru: string;
    patronymic_ru: string | null;
    first_name_en: string;
    last_name_en: string;
    isu_id: number | null;
    phone: string | null;
    email: string | null;
    telegram_username: string | null;
    is_admin: boolean;
};

export type VolunteersApiV1AuthSchemasUserResponse = {
    user_id: number;
    first_name_ru: string;
    last_name_ru: string;
    first_name_en: string;
    last_name_en: string;
    is_admin: boolean;
    isu_id: number | null;
    patronymic_ru: string | null;
    phone: string | null;
    email: string | null;
    telegram_username: string | null;
};

export type AddAssessmentApiV1AdminAssessmentAddPostData = {
    body: AddAssessmentRequest;
    path?: never;
    query?: never;
    url: '/api/v1/admin/assessment/add';
};

export type AddAssessmentApiV1AdminAssessmentAddPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddAssessmentApiV1AdminAssessmentAddPostError = AddAssessmentApiV1AdminAssessmentAddPostErrors[keyof AddAssessmentApiV1AdminAssessmentAddPostErrors];

export type AddAssessmentApiV1AdminAssessmentAddPostResponses = {
    /**
     * Successful Response
     */
    200: AddAssessmentResponse;
    /**
     * Returned when assessment successfully added
     */
    201: AddAssessmentResponse;
};

export type AddAssessmentApiV1AdminAssessmentAddPostResponse = AddAssessmentApiV1AdminAssessmentAddPostResponses[keyof AddAssessmentApiV1AdminAssessmentAddPostResponses];

export type EditAssessmentApiV1AdminAssessmentAssessmentIdEditPostData = {
    body: EditAssessmentRequest;
    path: {
        assessment_id: number;
    };
    query?: never;
    url: '/api/v1/admin/assessment/{assessment_id}/edit';
};

export type EditAssessmentApiV1AdminAssessmentAssessmentIdEditPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EditAssessmentApiV1AdminAssessmentAssessmentIdEditPostError = EditAssessmentApiV1AdminAssessmentAssessmentIdEditPostErrors[keyof EditAssessmentApiV1AdminAssessmentAssessmentIdEditPostErrors];

export type EditAssessmentApiV1AdminAssessmentAssessmentIdEditPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteAssessmentApiV1AdminAssessmentAssessmentIdDeleteData = {
    body?: never;
    path: {
        assessment_id: number;
    };
    query?: never;
    url: '/api/v1/admin/assessment/{assessment_id}';
};

export type DeleteAssessmentApiV1AdminAssessmentAssessmentIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteAssessmentApiV1AdminAssessmentAssessmentIdDeleteError = DeleteAssessmentApiV1AdminAssessmentAssessmentIdDeleteErrors[keyof DeleteAssessmentApiV1AdminAssessmentAssessmentIdDeleteErrors];

export type DeleteAssessmentApiV1AdminAssessmentAssessmentIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteAssessmentApiV1AdminAssessmentAssessmentIdDeleteResponse = DeleteAssessmentApiV1AdminAssessmentAssessmentIdDeleteResponses[keyof DeleteAssessmentApiV1AdminAssessmentAssessmentIdDeleteResponses];

export type GetUserDayAssessmentsApiV1AdminAssessmentUserDayUserDayIdGetData = {
    body?: never;
    path: {
        user_day_id: number;
    };
    query?: never;
    url: '/api/v1/admin/assessment/user-day/{user_day_id}';
};

export type GetUserDayAssessmentsApiV1AdminAssessmentUserDayUserDayIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserDayAssessmentsApiV1AdminAssessmentUserDayUserDayIdGetError = GetUserDayAssessmentsApiV1AdminAssessmentUserDayUserDayIdGetErrors[keyof GetUserDayAssessmentsApiV1AdminAssessmentUserDayUserDayIdGetErrors];

export type GetUserDayAssessmentsApiV1AdminAssessmentUserDayUserDayIdGetResponses = {
    /**
     * Successful Response
     */
    200: AssessmentsResponse;
};

export type GetUserDayAssessmentsApiV1AdminAssessmentUserDayUserDayIdGetResponse = GetUserDayAssessmentsApiV1AdminAssessmentUserDayUserDayIdGetResponses[keyof GetUserDayAssessmentsApiV1AdminAssessmentUserDayUserDayIdGetResponses];

export type GetYearDaysApiV1AdminDayYearYearIdGetData = {
    body?: never;
    path: {
        year_id: number;
    };
    query?: never;
    url: '/api/v1/admin/day/year/{year_id}';
};

export type GetYearDaysApiV1AdminDayYearYearIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetYearDaysApiV1AdminDayYearYearIdGetError = GetYearDaysApiV1AdminDayYearYearIdGetErrors[keyof GetYearDaysApiV1AdminDayYearYearIdGetErrors];

export type GetYearDaysApiV1AdminDayYearYearIdGetResponses = {
    /**
     * Successful Response
     */
    200: Array<DayOutAdmin>;
};

export type GetYearDaysApiV1AdminDayYearYearIdGetResponse = GetYearDaysApiV1AdminDayYearYearIdGetResponses[keyof GetYearDaysApiV1AdminDayYearYearIdGetResponses];

export type AddDayApiV1AdminDayAddPostData = {
    body: AddDayRequest;
    path?: never;
    query?: never;
    url: '/api/v1/admin/day/add';
};

export type AddDayApiV1AdminDayAddPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddDayApiV1AdminDayAddPostError = AddDayApiV1AdminDayAddPostErrors[keyof AddDayApiV1AdminDayAddPostErrors];

export type AddDayApiV1AdminDayAddPostResponses = {
    /**
     * Successful Response
     */
    200: AddDayResponse;
    /**
     * Returned when day successfully added
     */
    201: AddDayResponse;
};

export type AddDayApiV1AdminDayAddPostResponse = AddDayApiV1AdminDayAddPostResponses[keyof AddDayApiV1AdminDayAddPostResponses];

export type EditDayApiV1AdminDayDayIdEditPostData = {
    body: EditDayRequest;
    path: {
        day_id: number;
    };
    query?: never;
    url: '/api/v1/admin/day/{day_id}/edit';
};

export type EditDayApiV1AdminDayDayIdEditPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EditDayApiV1AdminDayDayIdEditPostError = EditDayApiV1AdminDayDayIdEditPostErrors[keyof EditDayApiV1AdminDayDayIdEditPostErrors];

export type EditDayApiV1AdminDayDayIdEditPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CopyAssignmentsApiV1AdminDayCopyAssignmentsPostData = {
    body: CopyAssignmentsRequest;
    path?: never;
    query?: never;
    url: '/api/v1/admin/day/copy-assignments';
};

export type CopyAssignmentsApiV1AdminDayCopyAssignmentsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CopyAssignmentsApiV1AdminDayCopyAssignmentsPostError = CopyAssignmentsApiV1AdminDayCopyAssignmentsPostErrors[keyof CopyAssignmentsApiV1AdminDayCopyAssignmentsPostErrors];

export type CopyAssignmentsApiV1AdminDayCopyAssignmentsPostResponses = {
    /**
     * Successful Response
     */
    200: CopyAssignmentsResponse;
};

export type CopyAssignmentsApiV1AdminDayCopyAssignmentsPostResponse = CopyAssignmentsApiV1AdminDayCopyAssignmentsPostResponses[keyof CopyAssignmentsApiV1AdminDayCopyAssignmentsPostResponses];

export type AddHallApiV1AdminHallAddPostData = {
    body: AddHallRequest;
    path?: never;
    query?: never;
    url: '/api/v1/admin/hall/add';
};

export type AddHallApiV1AdminHallAddPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddHallApiV1AdminHallAddPostError = AddHallApiV1AdminHallAddPostErrors[keyof AddHallApiV1AdminHallAddPostErrors];

export type AddHallApiV1AdminHallAddPostResponses = {
    /**
     * Successful Response
     */
    200: AddHallResponse;
    /**
     * Returned when hall successfully added
     */
    201: AddHallResponse;
};

export type AddHallApiV1AdminHallAddPostResponse = AddHallApiV1AdminHallAddPostResponses[keyof AddHallApiV1AdminHallAddPostResponses];

export type EditHallApiV1AdminHallHallIdEditPostData = {
    body: EditHallRequest;
    path: {
        hall_id: number;
    };
    query?: never;
    url: '/api/v1/admin/hall/{hall_id}/edit';
};

export type EditHallApiV1AdminHallHallIdEditPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EditHallApiV1AdminHallHallIdEditPostError = EditHallApiV1AdminHallHallIdEditPostErrors[keyof EditHallApiV1AdminHallHallIdEditPostErrors];

export type EditHallApiV1AdminHallHallIdEditPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetYearHallsApiV1AdminHallYearYearIdGetData = {
    body?: never;
    path: {
        year_id: number;
    };
    query?: never;
    url: '/api/v1/admin/hall/year/{year_id}';
};

export type GetYearHallsApiV1AdminHallYearYearIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetYearHallsApiV1AdminHallYearYearIdGetError = GetYearHallsApiV1AdminHallYearYearIdGetErrors[keyof GetYearHallsApiV1AdminHallYearYearIdGetErrors];

export type GetYearHallsApiV1AdminHallYearYearIdGetResponses = {
    /**
     * Successful Response
     */
    200: Array<HallOut>;
};

export type GetYearHallsApiV1AdminHallYearYearIdGetResponse = GetYearHallsApiV1AdminHallYearYearIdGetResponses[keyof GetYearHallsApiV1AdminHallYearYearIdGetResponses];

export type AddPositionApiV1AdminPositionAddPostData = {
    body: AddPositionRequest;
    path?: never;
    query?: never;
    url: '/api/v1/admin/position/add';
};

export type AddPositionApiV1AdminPositionAddPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddPositionApiV1AdminPositionAddPostError = AddPositionApiV1AdminPositionAddPostErrors[keyof AddPositionApiV1AdminPositionAddPostErrors];

export type AddPositionApiV1AdminPositionAddPostResponses = {
    /**
     * Successful Response
     */
    200: AddPositionResponse;
    /**
     * Returned when position successfully added
     */
    201: AddPositionResponse;
};

export type AddPositionApiV1AdminPositionAddPostResponse = AddPositionApiV1AdminPositionAddPostResponses[keyof AddPositionApiV1AdminPositionAddPostResponses];

export type EditPositionApiV1AdminPositionPositionIdEditPostData = {
    body: EditPositionRequest;
    path: {
        position_id: number;
    };
    query?: never;
    url: '/api/v1/admin/position/{position_id}/edit';
};

export type EditPositionApiV1AdminPositionPositionIdEditPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EditPositionApiV1AdminPositionPositionIdEditPostError = EditPositionApiV1AdminPositionPositionIdEditPostErrors[keyof EditPositionApiV1AdminPositionPositionIdEditPostErrors];

export type EditPositionApiV1AdminPositionPositionIdEditPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetAllUsersApiV1AdminUserGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/user';
};

export type GetAllUsersApiV1AdminUserGetResponses = {
    /**
     * Successful Response
     */
    200: AllUsersResponse;
};

export type GetAllUsersApiV1AdminUserGetResponse = GetAllUsersApiV1AdminUserGetResponses[keyof GetAllUsersApiV1AdminUserGetResponses];

export type GetUserByIdApiV1AdminUserUserIdGetData = {
    body?: never;
    path: {
        user_id: number;
    };
    query?: never;
    url: '/api/v1/admin/user/{user_id}';
};

export type GetUserByIdApiV1AdminUserUserIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserByIdApiV1AdminUserUserIdGetError = GetUserByIdApiV1AdminUserUserIdGetErrors[keyof GetUserByIdApiV1AdminUserUserIdGetErrors];

export type GetUserByIdApiV1AdminUserUserIdGetResponses = {
    /**
     * Successful Response
     */
    200: VolunteersApiV1AdminUserSchemasUserResponse;
};

export type GetUserByIdApiV1AdminUserUserIdGetResponse = GetUserByIdApiV1AdminUserUserIdGetResponses[keyof GetUserByIdApiV1AdminUserUserIdGetResponses];

export type EditUserApiV1AdminUserUserIdEditPostData = {
    body: EditUserRequest;
    path: {
        user_id: number;
    };
    query?: never;
    url: '/api/v1/admin/user/{user_id}/edit';
};

export type EditUserApiV1AdminUserUserIdEditPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EditUserApiV1AdminUserUserIdEditPostError = EditUserApiV1AdminUserUserIdEditPostErrors[keyof EditUserApiV1AdminUserUserIdEditPostErrors];

export type EditUserApiV1AdminUserUserIdEditPostResponses = {
    /**
     * Successful Response
     */
    200: VolunteersApiV1AdminUserSchemasUserResponse;
};

export type EditUserApiV1AdminUserUserIdEditPostResponse = EditUserApiV1AdminUserUserIdEditPostResponses[keyof EditUserApiV1AdminUserUserIdEditPostResponses];

export type AddUserDayApiV1AdminUserDayAddPostData = {
    body: AddUserDayRequest;
    path?: never;
    query?: never;
    url: '/api/v1/admin/user-day/add';
};

export type AddUserDayApiV1AdminUserDayAddPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddUserDayApiV1AdminUserDayAddPostError = AddUserDayApiV1AdminUserDayAddPostErrors[keyof AddUserDayApiV1AdminUserDayAddPostErrors];

export type AddUserDayApiV1AdminUserDayAddPostResponses = {
    /**
     * Successful Response
     */
    200: AddUserDayResponse;
    /**
     * Returned when user day successfully added
     */
    201: AddUserDayResponse;
};

export type AddUserDayApiV1AdminUserDayAddPostResponse = AddUserDayApiV1AdminUserDayAddPostResponses[keyof AddUserDayApiV1AdminUserDayAddPostResponses];

export type EditPositionApiV1AdminUserDayUserDayIdEditPostData = {
    body: EditUserDayRequest;
    path: {
        user_day_id: number;
    };
    query?: never;
    url: '/api/v1/admin/user-day/{user_day_id}/edit';
};

export type EditPositionApiV1AdminUserDayUserDayIdEditPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EditPositionApiV1AdminUserDayUserDayIdEditPostError = EditPositionApiV1AdminUserDayUserDayIdEditPostErrors[keyof EditPositionApiV1AdminUserDayUserDayIdEditPostErrors];

export type EditPositionApiV1AdminUserDayUserDayIdEditPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteUserDayApiV1AdminUserDayUserDayIdDeleteData = {
    body?: never;
    path: {
        user_day_id: number;
    };
    query?: never;
    url: '/api/v1/admin/user-day/{user_day_id}';
};

export type DeleteUserDayApiV1AdminUserDayUserDayIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserDayApiV1AdminUserDayUserDayIdDeleteError = DeleteUserDayApiV1AdminUserDayUserDayIdDeleteErrors[keyof DeleteUserDayApiV1AdminUserDayUserDayIdDeleteErrors];

export type DeleteUserDayApiV1AdminUserDayUserDayIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteUserDayApiV1AdminUserDayUserDayIdDeleteResponse = DeleteUserDayApiV1AdminUserDayUserDayIdDeleteResponses[keyof DeleteUserDayApiV1AdminUserDayUserDayIdDeleteResponses];

export type GetDayAssignmentsApiV1AdminUserDayDayDayIdAssignmentsGetData = {
    body?: never;
    path: {
        day_id: number;
    };
    query?: never;
    url: '/api/v1/admin/user-day/day/{day_id}/assignments';
};

export type GetDayAssignmentsApiV1AdminUserDayDayDayIdAssignmentsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDayAssignmentsApiV1AdminUserDayDayDayIdAssignmentsGetError = GetDayAssignmentsApiV1AdminUserDayDayDayIdAssignmentsGetErrors[keyof GetDayAssignmentsApiV1AdminUserDayDayDayIdAssignmentsGetErrors];

export type GetDayAssignmentsApiV1AdminUserDayDayDayIdAssignmentsGetResponses = {
    /**
     * Successful Response
     */
    200: AssignmentsResponse;
};

export type GetDayAssignmentsApiV1AdminUserDayDayDayIdAssignmentsGetResponse = GetDayAssignmentsApiV1AdminUserDayDayDayIdAssignmentsGetResponses[keyof GetDayAssignmentsApiV1AdminUserDayDayDayIdAssignmentsGetResponses];

export type AddYearApiV1AdminYearAddPostData = {
    body: AddYearRequest;
    path?: never;
    query?: never;
    url: '/api/v1/admin/year/add';
};

export type AddYearApiV1AdminYearAddPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddYearApiV1AdminYearAddPostError = AddYearApiV1AdminYearAddPostErrors[keyof AddYearApiV1AdminYearAddPostErrors];

export type AddYearApiV1AdminYearAddPostResponses = {
    /**
     * Successful Response
     */
    200: AddYearResponse;
    /**
     * Returned when year successfully added
     */
    201: AddYearResponse;
};

export type AddYearApiV1AdminYearAddPostResponse = AddYearApiV1AdminYearAddPostResponses[keyof AddYearApiV1AdminYearAddPostResponses];

export type EditYearApiV1AdminYearYearIdEditPostData = {
    body: EditYearRequest;
    path: {
        year_id: number;
    };
    query?: never;
    url: '/api/v1/admin/year/{year_id}/edit';
};

export type EditYearApiV1AdminYearYearIdEditPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EditYearApiV1AdminYearYearIdEditPostError = EditYearApiV1AdminYearYearIdEditPostErrors[keyof EditYearApiV1AdminYearYearIdEditPostErrors];

export type EditYearApiV1AdminYearYearIdEditPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetUsersListApiV1AdminYearYearIdUsersGetData = {
    body?: never;
    path: {
        year_id: number;
    };
    query?: never;
    url: '/api/v1/admin/year/{year_id}/users';
};

export type GetUsersListApiV1AdminYearYearIdUsersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUsersListApiV1AdminYearYearIdUsersGetError = GetUsersListApiV1AdminYearYearIdUsersGetErrors[keyof GetUsersListApiV1AdminYearYearIdUsersGetErrors];

export type GetUsersListApiV1AdminYearYearIdUsersGetResponses = {
    /**
     * Successful Response
     */
    200: UserListResponse;
};

export type GetUsersListApiV1AdminYearYearIdUsersGetResponse = GetUsersListApiV1AdminYearYearIdUsersGetResponses[keyof GetUsersListApiV1AdminYearYearIdUsersGetResponses];

export type GetYearPositionsApiV1AdminYearYearIdPositionsGetData = {
    body?: never;
    path: {
        year_id: number;
    };
    query?: never;
    url: '/api/v1/admin/year/{year_id}/positions';
};

export type GetYearPositionsApiV1AdminYearYearIdPositionsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetYearPositionsApiV1AdminYearYearIdPositionsGetError = GetYearPositionsApiV1AdminYearYearIdPositionsGetErrors[keyof GetYearPositionsApiV1AdminYearYearIdPositionsGetErrors];

export type GetYearPositionsApiV1AdminYearYearIdPositionsGetResponses = {
    /**
     * Successful Response
     */
    200: Array<PositionOut>;
};

export type GetYearPositionsApiV1AdminYearYearIdPositionsGetResponse = GetYearPositionsApiV1AdminYearYearIdPositionsGetResponses[keyof GetYearPositionsApiV1AdminYearYearIdPositionsGetResponses];

export type GetRegistrationFormsApiV1AdminYearYearIdRegistrationFormsGetData = {
    body?: never;
    path: {
        year_id: number;
    };
    query?: never;
    url: '/api/v1/admin/year/{year_id}/registration-forms';
};

export type GetRegistrationFormsApiV1AdminYearYearIdRegistrationFormsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRegistrationFormsApiV1AdminYearYearIdRegistrationFormsGetError = GetRegistrationFormsApiV1AdminYearYearIdRegistrationFormsGetErrors[keyof GetRegistrationFormsApiV1AdminYearYearIdRegistrationFormsGetErrors];

export type GetRegistrationFormsApiV1AdminYearYearIdRegistrationFormsGetResponses = {
    /**
     * Successful Response
     */
    200: RegistrationFormsResponse;
};

export type GetRegistrationFormsApiV1AdminYearYearIdRegistrationFormsGetResponse = GetRegistrationFormsApiV1AdminYearYearIdRegistrationFormsGetResponses[keyof GetRegistrationFormsApiV1AdminYearYearIdRegistrationFormsGetResponses];

export type SaveDayAttendanceApiV1AttendanceSavePostData = {
    body: SaveDayAttendanceRequest;
    path?: never;
    query?: never;
    url: '/api/v1/attendance/save';
};

export type SaveDayAttendanceApiV1AttendanceSavePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SaveDayAttendanceApiV1AttendanceSavePostError = SaveDayAttendanceApiV1AttendanceSavePostErrors[keyof SaveDayAttendanceApiV1AttendanceSavePostErrors];

export type SaveDayAttendanceApiV1AttendanceSavePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetAllAttendanceApiV1AttendanceYearIdAllGetData = {
    body?: never;
    path: {
        year_id: number;
    };
    query?: never;
    url: '/api/v1/attendance/{year_id}/all';
};

export type GetAllAttendanceApiV1AttendanceYearIdAllGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAllAttendanceApiV1AttendanceYearIdAllGetError = GetAllAttendanceApiV1AttendanceYearIdAllGetErrors[keyof GetAllAttendanceApiV1AttendanceYearIdAllGetErrors];

export type GetAllAttendanceApiV1AttendanceYearIdAllGetResponses = {
    /**
     * Successful Response
     */
    200: AllAttendanceResponse;
};

export type GetAllAttendanceApiV1AttendanceYearIdAllGetResponse = GetAllAttendanceApiV1AttendanceYearIdAllGetResponses[keyof GetAllAttendanceApiV1AttendanceYearIdAllGetResponses];

export type RegisterApiV1AuthTelegramRegisterPostData = {
    body: RegistrationRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/telegram/register';
};

export type RegisterApiV1AuthTelegramRegisterPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterApiV1AuthTelegramRegisterPostError = RegisterApiV1AuthTelegramRegisterPostErrors[keyof RegisterApiV1AuthTelegramRegisterPostErrors];

export type RegisterApiV1AuthTelegramRegisterPostResponses = {
    /**
     * Successful Response
     */
    200: SuccessfulLoginResponse;
};

export type RegisterApiV1AuthTelegramRegisterPostResponse = RegisterApiV1AuthTelegramRegisterPostResponses[keyof RegisterApiV1AuthTelegramRegisterPostResponses];

export type MigrateApiV1AuthTelegramMigratePostData = {
    body: TelegramMigrateRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/telegram/migrate';
};

export type MigrateApiV1AuthTelegramMigratePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MigrateApiV1AuthTelegramMigratePostError = MigrateApiV1AuthTelegramMigratePostErrors[keyof MigrateApiV1AuthTelegramMigratePostErrors];

export type MigrateApiV1AuthTelegramMigratePostResponses = {
    /**
     * Successful Response
     */
    200: SuccessfulLoginResponse;
};

export type MigrateApiV1AuthTelegramMigratePostResponse = MigrateApiV1AuthTelegramMigratePostResponses[keyof MigrateApiV1AuthTelegramMigratePostResponses];

export type LoginApiV1AuthTelegramLoginPostData = {
    body: TelegramLoginRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/telegram/login';
};

export type LoginApiV1AuthTelegramLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginApiV1AuthTelegramLoginPostError = LoginApiV1AuthTelegramLoginPostErrors[keyof LoginApiV1AuthTelegramLoginPostErrors];

export type LoginApiV1AuthTelegramLoginPostResponses = {
    /**
     * Successful Response
     */
    200: SuccessfulLoginResponse | ErrorLoginResponse;
};

export type LoginApiV1AuthTelegramLoginPostResponse = LoginApiV1AuthTelegramLoginPostResponses[keyof LoginApiV1AuthTelegramLoginPostResponses];

export type RefreshApiV1AuthRefreshPostData = {
    body: RefreshTokenRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/refresh';
};

export type RefreshApiV1AuthRefreshPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RefreshApiV1AuthRefreshPostError = RefreshApiV1AuthRefreshPostErrors[keyof RefreshApiV1AuthRefreshPostErrors];

export type RefreshApiV1AuthRefreshPostResponses = {
    /**
     * Successful Response
     */
    200: SuccessfulLoginResponse | ErrorLoginResponse;
};

export type RefreshApiV1AuthRefreshPostResponse = RefreshApiV1AuthRefreshPostResponses[keyof RefreshApiV1AuthRefreshPostResponses];

export type MeApiV1AuthMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me';
};

export type MeApiV1AuthMeGetResponses = {
    /**
     * Successful Response
     */
    200: VolunteersApiV1AuthSchemasUserResponse;
};

export type MeApiV1AuthMeGetResponse = MeApiV1AuthMeGetResponses[keyof MeApiV1AuthMeGetResponses];

export type UpdateUserApiV1AuthUpdatePostData = {
    body: UserUpdateRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/update';
};

export type UpdateUserApiV1AuthUpdatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserApiV1AuthUpdatePostError = UpdateUserApiV1AuthUpdatePostErrors[keyof UpdateUserApiV1AuthUpdatePostErrors];

export type UpdateUserApiV1AuthUpdatePostResponses = {
    /**
     * Successful Response
     */
    200: VolunteersApiV1AuthSchemasUserResponse;
};

export type UpdateUserApiV1AuthUpdatePostResponse = UpdateUserApiV1AuthUpdatePostResponses[keyof UpdateUserApiV1AuthUpdatePostResponses];

export type GetYearsApiV1YearGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/year/';
};

export type GetYearsApiV1YearGetResponses = {
    /**
     * Successful Response
     */
    200: YearsResponse;
};

export type GetYearsApiV1YearGetResponse = GetYearsApiV1YearGetResponses[keyof GetYearsApiV1YearGetResponses];

export type GetFormYearApiV1YearYearIdGetData = {
    body?: never;
    path: {
        year_id: number;
    };
    query?: never;
    url: '/api/v1/year/{year_id}';
};

export type GetFormYearApiV1YearYearIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetFormYearApiV1YearYearIdGetError = GetFormYearApiV1YearYearIdGetErrors[keyof GetFormYearApiV1YearYearIdGetErrors];

export type GetFormYearApiV1YearYearIdGetResponses = {
    /**
     * Successful Response
     */
    200: ApplicationFormYearSavedResponse;
};

export type GetFormYearApiV1YearYearIdGetResponse = GetFormYearApiV1YearYearIdGetResponses[keyof GetFormYearApiV1YearYearIdGetResponses];

export type SaveFormYearApiV1YearYearIdPostData = {
    body: ApplicationFormYearSaveRequest;
    path: {
        year_id: number;
    };
    query?: never;
    url: '/api/v1/year/{year_id}';
};

export type SaveFormYearApiV1YearYearIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SaveFormYearApiV1YearYearIdPostError = SaveFormYearApiV1YearYearIdPostErrors[keyof SaveFormYearApiV1YearYearIdPostErrors];

export type SaveFormYearApiV1YearYearIdPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
    /**
     * Returned when user signed up form for the first time
     */
    201: unknown;
    /**
     * Returned when user updated form
     */
    204: void;
};

export type SaveFormYearApiV1YearYearIdPostResponse = SaveFormYearApiV1YearYearIdPostResponses[keyof SaveFormYearApiV1YearYearIdPostResponses];

export type GetDayAssignmentsApiV1YearYearIdDaysDayIdAssignmentsGetData = {
    body?: never;
    path: {
        year_id: number;
        day_id: number;
    };
    query?: never;
    url: '/api/v1/year/{year_id}/days/{day_id}/assignments';
};

export type GetDayAssignmentsApiV1YearYearIdDaysDayIdAssignmentsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDayAssignmentsApiV1YearYearIdDaysDayIdAssignmentsGetError = GetDayAssignmentsApiV1YearYearIdDaysDayIdAssignmentsGetErrors[keyof GetDayAssignmentsApiV1YearYearIdDaysDayIdAssignmentsGetErrors];

export type GetDayAssignmentsApiV1YearYearIdDaysDayIdAssignmentsGetResponses = {
    /**
     * Successful Response
     */
    200: DayAssignmentsResponse;
};

export type GetDayAssignmentsApiV1YearYearIdDaysDayIdAssignmentsGetResponse = GetDayAssignmentsApiV1YearYearIdDaysDayIdAssignmentsGetResponses[keyof GetDayAssignmentsApiV1YearYearIdDaysDayIdAssignmentsGetResponses];

export type HealthCheckHcGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/hc';
};

export type HealthCheckHcGetResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type HealthCheckHcGetResponse = HealthCheckHcGetResponses[keyof HealthCheckHcGetResponses];

export type ProxyPathGetData = {
    body?: never;
    path: {
        path: string;
    };
    query?: never;
    url: '/{path}';
};

export type ProxyPathGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProxyPathGetError = ProxyPathGetErrors[keyof ProxyPathGetErrors];

export type ProxyPathGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseURL: 'http://localhost:8000' | (string & {});
};
